source "https://www.rubydocs.org"

gem "sinatra"
gem "sinatra/reloader"
gem "mustache"
gem "pg"
gem "mustache"
gem "twilio-ruby"
gem "sendgrid-ruby"
gem "will_paginate"
gem "will_paginate/active_record"
gem "redcarpet"